### ISSUE TITLE
Demo code misspelling for meta element HandheldFriendly

### ISSUE THREAD

**Issue by JamesSkemp** [eugenioclrc/phaser-touch-control-plugin#2]
Hello.

I was looking at your project this morning and found a misspelling in the demo's main index.html on line 8. You have:

    <meta name="HandheldFriendly" cnotent="true" />

That should be:

    <meta name="HandheldFriendly" content="true" />

Doing a bit of research, it appears this effectively isn't that important these days, but ...

**Comment by eugenioclrc** [comment]
thanks @JamesSkemp!
